### ISSUE TITLE
Nested resources with id-less endpoints

### ISSUE THREAD

**Issue by kenborge** [jmdobry/angular-data#292]
Is there anyway to setup a nested resource that will create the query
```GET /customer/<id>/bill```
From what i have figured out so far it's pretty easy to set it up on the form
```GET /customer/<id>/bill/<bill-id>```

(In my concrete usecase the bill actually has an ID, but the ID is the same as the customer id, and the API only uses the customer to find the bill resource to return)

**Comment by jmdobry** [comment]
`/customer/<id>/bill` is the url that will be used (expects an array of objects) when you do `findAll`, `updateAll`, `destroyAll`, `/customer/<id>/bill/<bill-id>` is the url that will be used (expects a single object) for `find`, `update`, `destroy`, etc.

------

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, Angular-data, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/angular-data).
