### ISSUE TITLE
Creating new instances:  I don't have a server id yet!

### ISSUE THREAD

**Issue by markmarijnissen** [jmdobry/angular-data#298]
When I create a new instance on the client, I don't know the ID yet, because the server will assign the ID.

However, If I don't have an ID, I cannot inject it into the Memory store.
If I can't inject it into the Memory store, I cannot load relations.

If I assign it a temporary client-side ID, AngularData will try to update (instead of create). 
Also, when the server answers with a different ID, all instances need to be replaced (i.e. clientside-id -> server-id).

What is the AngularData way of solving this?

**Comment by jmdobry** [comment]
To prevent the update instead of the create:

- `DSProvider.defaults.upsert = false`
- or `MyResource = DS.defineResource({ name: 'myResource', upsert: false, ... })`
- or `MyResource.create(instance, { upsert: false })`

When the object returned by the server to `create` contains a different id, angular-data should use that new id for the instance.

**Comment by markmarijnissen** [comment]
Thanks! Two more questions:

1. Did I understand correctly: when server changes ID, the old ID is not available anymore?
2. Can I write my own upsert logic? i.e.

```javascript
if(typeof id === "string" and id[0] === 'c') { 
    // create
} else {
    // update
}
````

**Comment by jmdobry** [comment]
1. Right
2. Sure

```js
var Resource = DS.defineResource({
  name: 'resource'
});

Resource.customCreate = function (attrs, options) {
  var id = attrs[Resource.idAttribute];
  if (typeof id === 'string' && id.length && id[0] === 'c') {
    return this.create(attrs, options);
  } else {
    return this.update(id, attrs, options);
  }
});
```
