### ISSUE TITLE
Different endpoints for different actions; dynamic endpoints

### ISSUE THREAD

**Issue by JosephBuchma** [jmdobry/angular-data#303]
Hi.
For example, I have *User* model with endpoint `/users/`, and *Group* model with endpoint `/groups/`. User have m2m relation with Group. Request for fetching associated groups looks like `/users/:id/groups`.
**Question**: how to change *Group* endpoint just for particular GET request?

**Comment by jmdobry** [comment]
```js
User.findAllGroups = function (id, params) {
  return DSHttpAdapter.GET('/users/' + id + '/groups', { params: params }).then(function (data) {
    return DS.defaults.deserialize(User.name, data);
  }).then(function (groups) {
    groups = Group.inject(groups);
    if (User.get(id)) {
      User.get(id).groups = groups;
    }
    return groups;
});
```

See also [here](https://groups.google.com/forum/?fromgroups#!searchin/angular-data/many/angular-data/o5UK8VYq680/eiQ5_mlzShgJ).

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, Angular-data, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/angular-data).

**Comment by demisx** [comment]
Calling `DS.defaults.deserialize(...)` return `undefined is not a function` error. Am I missing something?

**Comment by demisx** [comment]
Never mind. I've just upgraded to `1.6.1` and the error is gone.

**Comment by jmdobry** [comment]
What you're missing is [in the docs](http://www.js-data.io/docs/dshttpadapter#default-settings) where it says deserialize is an option for the http adapter. `DSHttpAdapter.defaults.deserialize(...)` ought to work better.

**Comment by demisx** [comment]
Yeah, I was following the example in this issue first and got that error. Switching to `DSHttpAdapter.defaults.deserialize` made it work.

**Comment by VenkatRamReddyK** [comment]
Accessing //  `GET /users/4/settings/ui `
[Plunker](http://plnkr.co/edit/sK9RABGVWIZ6AcgOei1z?p=preview)

```

(function(angular) {
  'use strict';

angular.module('xmpl', ['angular-data.DS'])
.service('User', function(DS) {
  return DS.defineResource({
    name: 'users', 
    endpoint:'users',
    computed: {
          id:function(){return 4;}
        },
     actions: { 
         count: {method: 'GET', isArray: false}
      }
  });
})
.service('Usersettings', function(DS, User) {
  return DS.defineResource({
        name: 'settingsui',
        endpoint:'settings/ui',
        computed: {
          id:function(){return 4;}
        },
        relations: {
          belongsTo: {
            users: {
              parent: true,
              localKey: 'userId',
              localField: 'users'
            }
          }
        }
      });
})
  .run(function(Usersettings, User) {

    Usersettings.findAll({ userId: 4 }). // GET /users/4/settings/ui
      then(function (response) {
          console.log(response);
      }).catch(function (response) {
          console.log(response);
      });
      
  })
})(window.angular);

```
